version: '3'

services:
  registry:
    image: registry:latest
    restart: always
    ports:
    - 5000:5000
    environment:
     REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
     - registry_data:/data
  proxy:
    image: nginx:latest
    restart: always
    depends_on:
     - registry
    volumes:
     - ./nginx:/etc/nginx/conf.d/
     - ./certs/:/etc/nginx/ssl/
    ports:
     - 80:80
     - 443:443
volumes:
  registry_data: {}

